#ifndef __SOUNDS_H__
#define __SOUNDS_H__

class Sounds
{
public:
	static constexpr char* RESOURCE_FILE_NAMES[] = {
		"aiee.wav", // 0
		"Alarm.wav",
		"barFight.wav",
		"bridge_creak2.wav",
		"canals1.wav",
		"Chicken_Attack.wav",
		"Chicken_Death.wav",
		"Chicken_Idle.wav",
		"Chicken_Kicked.wav",
		"Dialog_Help.wav",
		"Dialog_Popup.wav", // 10
		"Door_Cell.wav",
		"Door_Close.wav",
		"Door_Locked.wav",
		"Door_Open.wav",
		"Door_Unlocked.wav",
		"Door_Wood_Close.wav",
		"Door_Wood_Open.wav",
		"dripping_r.wav",
		"earthquake.wav",
		"Elecrocute.wav", // 20
		"Elevator.wav",
		"EliteGuard_Alert.wav",
		"EliteGuard_Death.wav",
		"EliteGuard_Pain.wav",
		"fire1.wav",
		"firesoft.wav",
		"fl_fire.wav",
		"forest_amb_01.wav",
		"fuel.wav",
		"fuelmotor1.wav", // 30
		"Gib.wav",
		"Gib_Stone.wav",
		"Gib_Wood.wav",
		"gq_alarm_loop.wav",
		"growl1.wav",
		"growl2.wav",
		"growl3.wav",
		"gurp2.wav",
		"Guten_Tag.wav",
		"GYeah.wav",  // 40
		"Harbinger_Alert.wav",
		"Harbinger_Charge.wav",
		"Harbinger_Claw.wav",
		"Harbinger_Death.wav",
		"Harbinger_Fireball.wav",
		"Harbinger_Laugh.wav",
		"Harbinger_Pain.wav",
		"Harbinger_Slurp.wav",
		"Harbinger_Vanquish.wav",
		"Item_Bookshelf.wav", // 50
		"Item_Food_Pickup.wav",
		"Item_Key_Pickup.wav",
		"Item_Mixing.wav",
		"Item_Pickup.wav",
		"Item_Sink.wav",
		"Item_Sink_Sparkle.wav",
		"Item_Treasure.wav",
		"Knight_Falling.wav",
		"leaves_rustle_loop1.wav",
		"me109_flight.wav", // 60
		"Meingut.wav",
		"Misc_Rumble.wav",
		"Monster_Alert1.wav",
		"Monster_Alert2.wav",
		"Monster_Alert3.wav",
		"Monster_Alert4.wav",
		"Monster_Pain1.wav",
		"Monster_Pain2.wav",
		"Monster_Pain3.wav",
		"Music_Boss1.wav", // 70
		"Music_Boss2.wav",
		"Music_Boss3.wav",
		"Music_Boss4.wav",
		"Music_Briefing.wav",
		"Music_Finale.wav",
		"Music_LevelUp.wav",
		"Music_Prologue.wav",
		"Music_Title.wav",
		"m_action.wav",
		"m_assault.wav", // 80
		"night_forest_amb.wav",
		"Olaric_Alert.wav",
		"Olaric_Attack1.wav",
		"Olaric_Attack2.wav",
		"Olaric_Death.wav",
		"Olaric_Pain.wav",
		"Player_Death.wav",
		"Player_Gasp.wav",
		"Player_Gurp.wav",
		"Player_Pain.wav", // 90
		"pool_drip.wav",
		"Skeleton_Alert.wav",
		"Skeleton_Attack.wav",
		"Skeleton_Death.wav",
		"Skeleton_Pain.wav",
		"Slap.wav",
		"snooper_reload.wav",
		"Soldat_Death.wav",
		"Soldier_Alert.wav",
		"Soldier_Death.wav", // 100
		"Soldier_Death2.wav",
		"Soldier_Pain.wav",
		"Spikes.wav",
		"splashes.wav",
		"Steam.wav",
		"SuperSoldier_Alert.wav",
		"SuperSoldier_Death.wav",
		"SuperSoldier_Pain.wav",
		"Switch_Jammed.wav",
		"Switch_Pull.wav", // 110
		"tankmove2.wav",
		"tesla_field_loop.wav",
		"thompson.wav",
		"Tormentor_Alert.wav",
		"Tormentor_Attack1.wav",
		"Tormentor_Attack2.wav",
		"Tormentor_Death.wav",
		"Tormentor_Pain.wav",
		"tortured_souls_loop.wav",
		"Trap_Trigger.wav", // 120
		"war_giant2.wav",
		"waterfall.wav",
		"Water_In.wav",
		"Water_Out.wav",
		"Weapon_Change.wav",
		"Weapon_Dynamite_Exp.wav",
		"Weapon_Dynamite_Place.wav",
		"Weapon_FG42.wav",
		"Weapon_Flamethrower.wav",
		"Weapon_Kick.wav", // 130
		"Weapon_MP40.wav",
		"Weapon_NoAmmo.wav",
		"Weapon_Paratrooper.wav",
		"Weapon_Pistol.wav",
		"Weapon_Rocket.wav",
		"Weapon_Rocket_Exp.wav",
		"Weapon_Slap.wav",
		"Weapon_Slap_Air.wav",
		"Weapon_Sniper.wav",
		"Weapon_Sniper_Scope.wav", // 140
		"Weapon_Spear.wav",
		"Weapon_Sten.wav",
		"Weapon_Tesla.wav",
		"Weapon_Toilet_Pull.wav",
		"Weapon_Toilet_Smash.wav",
		"Weapon_Toilet_Throw.wav",
		"Weapon_Underwater.wav",
		"Weapon_Underwater_Miss.wav",
		"Weapon_Venom.wav",
		"Weapon_Wrench.wav", // 150
		"wind1.wav",
		"windcave.wav",
		"wind_whistle.wav",
		"xchoir2.wav",
		"x_action.wav",
		"Zombie_Alert.wav",
		"Zombie_Attack.wav",
		"Zombie_Attack1.wav",
		"Zombie_Attack2.wav", // 160
		"Zombie_Death.wav",
		"Zombie_Pain.wav"
	};
};

#endif
